'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Clock3, Heart, Loader2, MapPin, Search, Star, Tag, TrendingUp } from 'lucide-react';
import { formatNaira, formatTimeAgo, type DoAmWithCreator } from '@/lib/doam';
import { cn } from '@/lib/utils';

const categories = ['All', 'Errands', 'Delivery', 'Cleaning', 'Moving', 'Shopping', 'Household', 'Personal Help', 'Events', 'Repairs', 'Other'];
export default function ExplorePage() {
  const [doams, setDoams] = useState<DoAmWithCreator[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [sort, setSort] = useState<'recent' | 'reward' | 'popular'>('recent');
  const load = useCallback(async () => { setLoading(true); const query = new URLSearchParams({ sort, take: '50' }); if (search.trim()) query.set('search', search.trim()); if (category !== 'All') query.set('category', category); const response = await fetch(`/api/doams?${query}`, { cache: 'no-store' }); const body = await response.json().catch(() => null); setDoams(response.ok ? body.doams : []); setLoading(false); }, [category, search, sort]);
  useEffect(() => { const timeout = setTimeout(load, 200); return () => clearTimeout(timeout); }, [load]);
  return <div><div className="mb-6"><h1 className="text-2xl font-bold tracking-[-0.03em] text-[#111827] lg:text-3xl">Explore</h1><p className="mt-1 text-sm text-[#6b7280]">Discover DoAms across the community</p></div><div className="relative mb-5"><Search className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-[#8a9590]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search all DoAms" className="h-11 w-full rounded-xl border border-[#e4e9e6] bg-white pl-10 pr-4 text-sm outline-none" /></div><div className="mb-4 flex gap-2">{([{ key: 'recent', label: 'Most Recent', icon: Clock3 }, { key: 'reward', label: 'Highest Reward', icon: TrendingUp }, { key: 'popular', label: 'Most Liked', icon: Heart }] as const).map((tab) => { const Icon = tab.icon; return <button key={tab.key} onClick={() => setSort(tab.key)} className={cn('flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold', sort === tab.key ? 'bg-[#0e6b53] text-white' : 'border border-[#e1e8e4] bg-white text-[#6e7c74]')}><Icon className="h-3.5 w-3.5" />{tab.label}</button>; })}</div><div className="mb-5 flex gap-2 overflow-x-auto pb-1 scrollbar-none">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={cn('whitespace-nowrap rounded-full border px-3.5 py-1.5 text-xs font-semibold', category === item ? 'border-[#0e6b53] bg-[#0e6b53] text-white' : 'border-[#e1e8e4] bg-white text-[#6e7c74]')}>{item}</button>)}</div>{loading ? <div className="flex justify-center py-20"><Loader2 className="h-7 w-7 animate-spin text-[#0e6b53]" /></div> : doams.length ? <div className="grid gap-4 sm:grid-cols-2">{doams.map((doam) => <Card key={doam.id} doam={doam} />)}</div> : <div className="rounded-2xl border border-dashed border-[#cbdcd3] bg-white px-6 py-16 text-center"><h3 className="font-bold text-[#27352e]">No DoAms found</h3><p className="mt-1 text-sm text-[#89958f]">Try another search or category filter.</p></div>}</div>;
}
function Card({ doam }: { doam: DoAmWithCreator }) { return <Link href={`/doams/${doam.id}`} className="block"><article className="h-full rounded-2xl border border-[#e4e9e6] bg-white p-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#d8f6ea] text-xs font-bold text-[#0e6b53]">{doam.creator?.full_name?.charAt(0)?.toUpperCase() ?? 'U'}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#27352e]">{doam.creator?.full_name ?? 'Unknown'}</p><p className="text-xs text-[#89958f]">@{doam.creator?.username ?? 'user'}</p></div>{doam.creator?.rating_avg ? <span className="flex items-center gap-1 text-xs text-[#a86400]"><Star className="h-3.5 w-3.5 fill-current" />{doam.creator.rating_avg.toFixed(1)}</span> : null}</div><h3 className="mt-3 text-[16px] font-bold text-[#17221c]">{doam.title}</h3>{doam.description && <p className="mt-1.5 line-clamp-2 text-sm text-[#748079]">{doam.description}</p>}<div className="mt-3 flex gap-3 text-xs text-[#87938c]"><span className="flex items-center gap-1"><Tag className="h-3 w-3 text-[#0e6b53]" />{doam.category}</span>{doam.location_label && <span className="flex items-center gap-1"><MapPin className="h-3 w-3 text-[#0e6b53]" />{doam.location_label}</span>}</div><div className="mt-4 flex items-center justify-between border-t border-[#edf0ee] pt-3"><p className="text-lg font-bold text-[#0e6b53]">{formatNaira(doam.reward)}</p><div className="flex gap-3 text-xs text-[#89958f]"><span className="flex items-center gap-1"><Heart className="h-3.5 w-3.5" />{doam.like_count ?? 0}</span><span>{formatTimeAgo(doam.created_at)}</span></div></div></article></Link>; }
